version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - aws --version
      - aws ssm get-parameter --with-decryption --name mossverse-game-$NODE_ENV --region $AWS_DEFAULT_REGION | jq '.Parameter.Value' | sed 's/^.//;s/.$//' | perl -pe 's/\\n/\n/g' > ./GameBuild/.env.$NODE_ENV
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $NODE_ENV

  build:
    commands:    
      - echo Build started on `date`
      - echo Building the Game - Gem Quest
      - cd ./GameBuild
      - yarn install
      - yarn build:prod:gq

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: GameBuild/dist/gemQuest